version: "3.1"
services:
  db:
    container_name: MRA_DB
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/data:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Quintenps_mapleroyals_analytics
      MYSQL_DATABASE: mapleroyals_analytics
      MYSQL_USER: tiger
      MYSQL_PASSWORD: genesis30ftw

  backend:
    container_name: MRA_BACKEND
    image: quintenps/mapleroyals_backend
    build:
      context: ./src/backend
      dockerfile: ../../docker/backend/Dockerfile
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mapleroyals_analytics
      MYSQL_USER: tiger
      MYSQL_PASSWORD: genesis30ftw

  frontend:
    container_name: MRA_FRONTEND
    build:
      context: ./src/frontend
      dockerfile: ../../docker/frontend/Dockerfile
      args:
        VUE_APP_API_HOST: "http://localhost:3000"
    ports:
      - 80:80

volumes:
  db_data:
    driver: local
